### ISSUE TITLE
Constant for Euler's number (e)

### ISSUE THREAD

**Issue by hieuthi** [mauriciopoppe/interval-arithmetic#35]
Just found your function-plot library, thanks for the great job.

If possible, can you add a constant for Euler's number, it would be very useful for many scenarios.

https://www.w3schools.com/python/ref_math_e.asp

**Comment by donhatch** [comment]
I notice that Interval.constants.E is now the same interval as that returned by Interval.exp(new Interval.Interval(1)), which is technically correct but isn't as tight as it could be.  Perhaps it could be tightened so that its endpoints are two consecutive representable numbers (like Interval.constants.PI)?
