### ISSUE TITLE
Vertical connections for polylines

### ISSUE THREAD

**Issue by trafnar** [mauriciopoppe/interval-arithmetic#38]
I tried graphing a floor function (`Math.floor(x)`) with `graphType: 'polyline'` and noticed it has a vertical connection between the jump from the x=0 portion to x=1, but all other jumps do not display this connection line.

I'd like to display it, is there a setting to achieve that, or is this a limitation of how the system work?

<img width="413" alt="image" src="https://github.com/mauriciopoppe/interval-arithmetic/assets/6732/0290691b-1cf9-4fc0-bf28-eb7481728458">

```js
{
    graphType: 'polyline',
    fn: (scope) => Math.floor(scope.x),
}
```

Thanks for your work on this very useful tool!

**Comment by mauriciopoppe** [comment]
You've hit one of the use cases I designed this library for!

So with traditional arithmetic function plotters it's hard to plot vertical lines, a plotter usually swipes from left to right evaluating `f` with different places and then joins the results with a line:

- let `f(x) = floor(x)`
- `f(0.5) = 0`, so plot a line from some previous `(x,y)` to the point `(0.5, 0)`
- `f(0.999999999999999999) = 0`,  so plot a line from the point `(0.5)` to the point `(0.999999999999999999, 0)`
- `f(1.0) = 1`, so plot a line from the point `(0.9999999999999999, 0)` to the point `(1, 1)`

The above is correct until you start looking at functions that have asymptotes e.g. `g(x) = 1/x`

- let g(x) = 1/x
- `g(-0.0000005) = -2*10^6`, so plot a line from some previous `(x,y)` to the point `(-0.0000005, -2*10^6)`
- `g(0.0000005) = 2*10^6`,  so plot a line from the point `(-0.0000005, -2*10^6)` to the point `(0.0000005, 2*10^6)`

The last line is not good, because there's an asymptote, the graph is:

<img width="541" alt="image" src="https://github.com/mauriciopoppe/interval-arithmetic/assets/1616682/31fb120b-8d91-48ee-9734-cca841785e69">

As you see there's no line connecting the points, however with interval arithmetic it's possible  to do because the evaluation contains all possible points within a range instead of an evaluation at a single point.

Assuming that `[lo,hi]` represents an interval then evaluating `g([lo,hi]) = 1/[lo,hi]` means evaluating:

- `g(-0.0000005, 0.0000005) = inf`, in interval arithmetic a division with an interval that contains 0 is automatically infinity.

So we're good for `g([lo,hi]) = 1/[lo,hi]` in interval arithmetic. For the function you proposed `f(x) = floor(x)` assuming that it's instead an interval `f([lo,hi]) = floor([lo,hi])`

- `f(0.99999999, 1.0) = [floor(0.999), floor(1)] = [0, 1]` so it's an interval that goes from 0 to 1 vertically.

<img width="653" alt="image" src="https://github.com/mauriciopoppe/interval-arithmetic/assets/1616682/6b17048e-5825-49fe-bbcf-f7792e060bd2">

https://codesandbox.io/s/crazy-rosalind-29pl43

**Comment by trafnar** [comment]
I can't believe I got such a thorough answer so quickly, much appreciated. This worked for me.

**Comment by trafnar** [comment]
So you use this for a `floor` function

```js
return {
    lo: Math.floor(scope.x.lo),
    hi: Math.floor(scope.x.hi)
}
```

what do you use for the `y = 1/x` you mentioned above, if you want to connect the lines across the asymptote?

**Comment by mauriciopoppe** [comment]
For that function specifically `1/x` it'd be:

```
import Interval from 'interval-arithmetic'

...
      fn: function (scope) {
        if (Interval.zeroIn(scope.x)) {
          return {lo: -inf, hi: inf}  
        }
        return Interval.div(Interval.ONE, scope.x)
      }
```
